version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/rocky
hooks:
  BeforeInstall:
    - location: scripts/aws/install_lib_dependencies.sh
      timeout: 300
      runas: root
    - location: scripts/aws/install_rvm_passenger.sh
      timeout: 300
      runas: ec2-user