defaults:
<% if ENV['RAILS_ENV'] == "development" %>
  install_options: --source http://gems.github.com --source http://gems.rubyforge.org
<% else %>
  install_options: --no-ri --no-rdoc --source http://gems.github.com --source http://gems.rubyforge.org
<% end %>
gems:
- name: rake
  version: = 0.8.7
- name: rails
<% if ENV['RAILS_GEM_VERSION'] %>
  # To see more recent preview gems, run 'gem list rails --source=http://gems.rubyonrails.org --remote'
  # To see which of these correspond to a tag, run 'svn log http://svn.rubyonrails.org/rails/tags'
  version: <%= ENV['RAILS_GEM_VERSION'] %>
  install_options: -y --source=http://gems.rubyonrails.org
<% else %>
  version: = 2.3.2
<% end %>
- name: rubyist-aasm
  version: = 2.0.5
- name: authlogic
  version: = 2.1.1
- name: fastercsv
  version: = 1.5.0
- name: daemons
  version: = 1.0.10

- name: rspec
  version: = 1.2.7
- name: rspec-rails
  version: = 1.2.7
- name: rr
  version: = 0.10.10
- name: thoughtbot-factory_girl
  version: = 1.2.1
- name: nokogiri
  version: = 1.3.2
- name: pivotal-webrat
  version: = 0.4.4
  install_options: --source=http://gems.pivotallabs.com
- name: cucumber
  version: = 0.3.11
- name: selenium-client
  version: = 1.2.16
