defaults:
<% unless ENV['RAILS_ENV'] != "development" %>
  install_options: --no-ri --no-rdoc --source http://gems.github.com --source http://gems.rubyforge.org
<% else %>
  install_options: --source http://gems.github.com --source http://gems.rubyforge.org
<% end %>
gems:
- name: rake
  version: ~> 0.8.7
- name: rails
<% if ENV['RAILS_GEM_VERSION'] %>
  # To see more recent preview gems, run 'gem list rails --source=http://gems.rubyonrails.org --remote'
  # To see which of these correspond to a tag, run 'svn log http://svn.rubyonrails.org/rails/tags'
  version: <%= ENV['RAILS_GEM_VERSION'] %>
  install_options: -y --source=http://gems.rubyonrails.org
<% else %>
  version: 2.3.2
<% end %>
- name: rspec
  version: ~> 1.2.7
- name: rspec-rails
  version: ~> 1.2.7
- name: rr
  version: ~> 0.10.0
- name: rubyist-aasm
  version: ~> 2.0.5
- name: thoughtbot-factory_girl
  version: ~> 1.2.1
- name: nokogiri
  version: ~> 1.3.2
- name: webrat
  version: ~> 0.4.4
- name: cucumber
  version: ~> 0.3.11
