defaults:
  install_options: --no-ri --no-rdoc
gems:
- name: rake
  version: ~> 0.8.7
- name: rails
  <% if ENV['RAILS_GEM_VERSION'] %>
  # To see more recent preview gems, run 'gem list rails --source=http://gems.rubyonrails.org --remote'
  # To see which of these correspond to a tag, run 'svn log http://svn.rubyonrails.org/rails/tags'
  version: <%= ENV['RAILS_GEM_VERSION'] %>
  install_options: -y --source=http://gems.rubyonrails.org
  <% else %>
  version: 2.3.2
  <% end %>
- name: capistrano
  version: 2.5.3
- name: capistrano-ext
  version: 1.2.1
- name: rspec
  version: ~> 1.2.7
- name: rspec-rails
  version: ~> 1.2.7
