sms_short_code: 788683
terms_url: "https://www.rockthevote.org/mobile-terms-and-conditions/"
privacy_url: "https://www.rockthevote.org/privacy-policy/"
sponsor:
  allow_ask_for_volunteers: true
  barcode_prefix: "RTV"
  name: "Rock the Vote"
  url: "https://www.rockthevote.org"
  facebook_callback_url: <%= CGI.escape("https://www.rockthevote.org/register-to-vote/?source=fb") %>
  partner_signup_url: "https://www.rockthevote.org/resources/online-voter-registration-tool/"
  footer_link_base_url: "https://www.rockthevote.org/voter-registration/online-application-system"
  footer_copyright: "&copy; Copyright %d, Rock the Vote"
  partner_comarketing_text: |
    Numbers not as high as you'd like?
    <a href="https://www.rockthevote.org/resources/online-voter-registration-tool/" target="_blank">Here are some ways to help market your tool.</a>

from_address: "rocky@example.com"
default_url_host: "register.example.com"
ui_url_host: "register5.example.com"

blocks_configuration:
  states:
    - PA
    - VA
    - MI


# this URL (if present) is shown as a WIKI nav menu item in the Partner portal
partner_wiki_url: "http://wiki.rockthevote.com"

catalist:
  audience: catalist_api_mr_prod
  url: https://api.catalist.us
  auth_url: https://auth.catalist.us
  
admin:
  from_address: "alex.mekelburg@osetfoundation.org"
  branding_from: "Rock the Vote <info@rockthevote.com>"
  branding_to: "david@rockthevote.com, melissa@rockthevote.com"
  partner_status_to: "david@rockthevote.com, melissa@rockthevote.com, alex.mekelburg@osetfoundation.org"
  admin_recipients: "errors@rockthevote.com, alex.mekelburg@osetfoundation.org"
  translation_recipients: "david@rockthevote.com, alex.mekelburg@osetfoundation.org"

admin_username: 'admin'
widget_js_url:  'https://s3.amazonaws.com/ovr/widget_loader.js'

use_https: true
paperclip_options: 
  storage: "fog"
  path: ":rails_root/public/system/:attachment/:id/:style/:filename"
  url: "/system/:attachment/:id/:style/:filename"

mobile_redirect_url: https://register.rockthevote.com
mobile_browsers:
  - mobile
  - webos
  - blackberry
  - iphone
  
widget_loader_url: https://s3.amazonaws.com/ovr/widget_loader.js
hours_before_first_reminder: 24
hours_between_first_and_second_reminder: 24
hours_between_second_and_final_reminder: 48
minutes_before_abandoned: 30
# hours_before_first_reminder: 1
# hours_between_first_and_second_reminder: 1
# hours_between_second_and_final_reminder: 1
# minutes_before_abandoned: 30
ui_timeout_minutes: 30
pdf_expiration_days: 14
pdf_no_email_expiration_minutes: 10
partner_csv_expiration_minutes: 30

absentee_states:
  AK:
    online_req_url: https://absenteeballotapplication.alaska.gov/
    pdf_template: ak.pdf
  AL:
    pdf_template:
    pdf_url: https://www.sos.alabama.gov/sites/default/files/voter-pdfs/absentee/RegularAbsenteeAppFillable.pdf
  AR:
    pdf_template: ar.pdf
  AZ:
    online_req_url: https://my.arizona.vote/Early/ApplicationLogin.aspx
    pdf_template: az.pdf
  CA: {}
  CO: {}
  CT:
    pdf_template:
    pdf_url: https://portal.ct.gov/-/media/SOTS/ElectionServices/COVID-19/ED-3-English-Rev-2020.pdf
  DC: 
    online_req_url: https://www.vote4dc.com/ApplyInstructions/Absentee
    pdf_template: dc.pdf
    # pdf_template: Absentee-Request-Form-and-Information-030120-LM03-04-20_2.pdf
  DE:
    online_req_url: https://ivote.de.gov/voterlogin.aspx    
    pdf_template: absentee_ballot_application.pdf
  FL:
    online_req_url: https://dos.elections.myflorida.com/supervisors/    
  GA:
    pdf_template: ga.pdf
  HI: {}
  IA:
    pdf_template:
    pdf_url: https://sos.iowa.gov/elections/pdf/absenteeballotapp.pdf
  ID:
    online_req_url: https://elections.sos.idaho.gov/ElectionLink/ElectionLink/AbsenteeSearch.aspx
    pdf_template: #2020_Absentee_Request.pdf
    pdf_url: https://sos.idaho.gov/elect/clerk/forms/2020_Absentee_Request.pdf
  IL:
    pdf_template:
    pdf_url: https://elections.il.gov/ElectionOperations/VotingByMailAgreement.aspx
  IN:
    pdf_template:
    pdf_url: https://forms.in.gov/Download.aspx?id=8691
  KS:
    pdf_template:
    pdf_url: https://www.kssos.org/forms/elections/AV1.pdf
  KY: {}
  LA:
    online_req_url: https://voterportal.sos.la.gov/Home/VoterLogin
    pdf_template: la.pdf
  MA:
    pdf_template: ma.pdf
  MD:
    online_req_url: https://voterservices.elections.maryland.gov/OnlineVoterRegistration/VoterType
    pdf_template: md.pdf
    pdf_url: https://elections.maryland.gov/voting/documents/Special_Election_Absentee_Application.pdf 
  ME:
    online_req_url: https://www1.maine.gov/cgi-bin/online/AbsenteeBallot/online-form.pl
  MI:
    online_req_url: https://mvic.sos.state.mi.us/avapplication
    pdf_template: 
    pdf_url: https://www.michigan.gov/documents/AbsentVoterBallot_105377_7.pdf
  MN:
    online_req_url: https://mnvotes.sos.state.mn.us/ABRegistration/ABRegistrationStep1.aspx
  MO:
    pdf_template: mo.pdf
  MS: {}
  MT:
    pdf_template:
    pdf_url: https://sosmt.gov/Portals/142/Elections/Forms/Application-for-Absentee-Ballot.pdf
  NC:
    pdf_template:      
    pdf_url: https://s3.amazonaws.com/dl.ncsbe.gov/Forms/NCAbsenteeBallotRequestForm.pdf
  ND:
    online_req_url: https://vip.sos.nd.gov/absentee/
    pdf_template:
    pdf_url: https://www.nd.gov/eforms/Doc/sfn51468.pdf 
  NE:
    pdf_template:
    pdf_url: https://sos.nebraska.gov/sites/sos.nebraska.gov/files/doc/elections/earlyvote_app_fill.pdf
  NH:
    pdf_template: 
    pdf_url: http://sos.nh.gov/WorkArea/DownloadAsset.aspx?id=8589999327
  NJ:
    pdf_template:
    pdf_url: https://www.state.nj.us/state/elections/vote-by-mail.shtml
  NM:
    online_req_url: https://portal.sos.state.nm.us/OVR/WebPages/AbsenteeApplication.aspx
    pdf_template:
    pdf_url: https://realfileee3072ab0d43456cb15a51f7d82c77a2.s3.amazonaws.com/97e1ee9d-281c-412a-9a85-0ea2e65f70ff?AWSAccessKeyId=AKIAJBKPT2UF7EZ6B7YA&Expires=1594221251&Signature=MXa6eiIsNedMu%2BRVpWNkDOQdLOU%3D&response-content-disposition=inline%3B%20filename%3DNMAV%2009-2019.pdf&response-content-type=application%2Fpdf
  NV:
    pdf_template:
    pdf_url: https://www.nvsos.gov/sos/home/showdocument?id=8262
    counties:
      clark:
        online_req_url: https://www.nvsos.gov/sos/home/showdocument?id=8262
  NY:
    pdf_template:
    pdf_url: https://www.elections.ny.gov/NYSBOE/download/voting/AbsenteeBallot-English.pdf
  OH:
    pdf_template: oh.pdf
  OK:
    online_req_url: https://services.okelections.us/AbsenteeApplication/
  OR: {}      
  PA:
    online_req_url: https://www.pavoterservices.pa.gov/OnlineAbsenteeApplication/#/OnlineAbsenteeBegin
    pdf_template:
    pdf_url: https://www.votespa.com/Register-to-Vote/Documents/PADOS_MailInApplication.pdf
  RI:
    pdf_template:
    pdf_url: https://vote.sos.ri.gov/Content/Pdfs/General%20Mail%20Ballot%20Application%2011-3-2020.pdf
  SC:
    online_req_url: https://info.scvotes.sc.gov/eng/voterinquiry/VoterInformationRequest.aspx?PageMode=AbsenteeRequest
  SD:
    pdf_template:
    pdf_url: https://sdsos.gov/elections-voting/assets/AbsenteeBallotApplicationFillable.pdf
  TN:
    pdf_template:
    pdf_url: https://sos-tn-gov-files.tnsosfiles.com/2020%20Absentee%20Request%20-%20August.pdf
  TX:
    pdf_template: tx.pdf
  UT: {}  
  VA:
    online_req_url: https://vote.elections.virginia.gov/VoterInformation/Lookup/absentee
    pdf_template: va.pdf
  VT:
    online_req_url: https://mvp.sec.state.vt.us/
    pdf_template: vt.pdf
  WA: {}
  WI:
    online_req_url: https://myvote.wi.gov/en-US/VoteAbsentee
    pdf_template: wi.pdf
    pdf_url: https://elections.wi.gov/sites/elections.wi.gov/files/2020-07/EL-121%20Application%20for%20Absentee%20Ballot%20%282018-10%29-Fillable.pdf
  WV:
    online_req_url:
    pdf_template: 
    pdf_url: https://sos.wv.gov/FormSearch/Elections/Voter/Absentee%20Ballot%20Application.pdf
  WY:
    pdf_template: wy.pdf
  
ovr_states:
  AZ:
    redirect_to_online_reg_url: true
    require_id: false
    languages:
      - en
      - es    
  CA:
    redirect_to_online_reg_url: true
    api_settings:
      api_url: https://covrapi.sos.ca.gov/PostingEntityInterfaceService.svc
      api_key: <%= ENV['CA_API_KEY'] %>
      api_posting_entity_name: RTV
      debug_in_ui: false
      log_all_requests: false
      disclosures_url: https://covr.cdn.sos.ca.gov/discl/
      web_url_base: https://covr.sos.ca.gov
      disclosures_box_height: 170px
      web_agency_key: RTV
      custom_error_string: CUSTOM_COVR_ERROR
    require_age_confirmation: false
    require_id: false
    languages:
      - en
      - es
      - zh-tw
      - vi
      - ko
      - tl
      - ja
      - hi
      - km
      - th
  LA:
    redirect_to_online_reg_url: true
    languages:
      - en
  MN:
    redirect_to_online_reg_url: true
    require_id: false
    languages:
      - en
  NV:
    redirect_to_online_reg_url: true
    languages:
      - en
      - es
  AK:
    redirect_to_online_reg_url: true
    languages:
      - en
  AL:
    redirect_to_online_reg_url: true
    languages:
      - en
  CO:
    redirect_to_online_reg_url: true
    languages:
      - en
      - es
  CT:
    redirect_to_online_reg_url: true
    languages:
      - en
      - es
  DC:
    redirect_to_online_reg_url: true
    languages:
      - en
  DE:
    redirect_to_online_reg_url: true
    require_age_confirmation: true
    require_id: false
    languages:
      - en
  FL:
    redirect_to_online_reg_url: true
    languages:
      - en
      - es
  GA:
    redirect_to_online_reg_url: true
    languages:
      - en
  HI:
    redirect_to_online_reg_url: true
    languages:
      - en
  IL:
    redirect_to_online_reg_url: true
    languages:
      - en
      - es
  IN:
    redirect_to_online_reg_url: true
    languages:
      - en
  IA:
    redirect_to_online_reg_url: true
    languages:
      - en
  ID:
    redirect_to_online_reg_url: true
    languages:
      - en
  KS:
    redirect_to_online_reg_url: false # We have ks.html.erb that takes care of the redirect
    require_id: false
    languages:
      - en
  KY:
    redirect_to_online_reg_url: true
    languages:
      - en
  MA:
    redirect_to_online_reg_url: true
    languages:
      - en
  MD:
    redirect_to_online_reg_url: true
    languages:
      - en
      - es
  MI:
    api_settings:
      api_url: https://test-mvicapi.sos.state.mi.us
    redirect_to_online_reg_url: true
    require_age_confirmation: true
    languages:
      - en
    
  MO:
    redirect_to_online_reg_url: true
    require_age_confirmation: true
    require_id: false
    languages:
      - en
  NC:
    redirect_to_online_reg_url: true
    languages:
      - en
  NE:
    redirect_to_online_reg_url: true
    languages:
      - en
      - es
  NM:
    redirect_to_online_reg_url: true
    languages:
      - en
      - es
  NY:
    redirect_to_online_reg_url: true
    languages:
      - en
      - es
  OH:
    redirect_to_online_reg_url: true
    languages:
      - en
      - es
  OR:
    redirect_to_online_reg_url: true
    languages:
      - en
      - es
  PA:
    require_age_confirmation: true
    grommet_min_version: "3.5.0"
    registration_deadline: 2020-11-03 # Must be YYYY-MM-DD format and use election date not reg deadline date for this one!
    api_settings:
      api_url: "https://paovrwebapi.votespa.com/SureOVRWebAPI/api/ovr?JSONv2&sysparm_AuthKey=<%= ENV['PA_API_KEY'] %>&sysparm_action=SETAPPLICATION&sysparm_Language=0"
      api_key: <%= ENV['PA_API_KEY'] %>
      canvassing_session_timeout_minutes: 1440
      canvassing_validation_timeout_minutes: 2880
    redirect_to_online_reg_url: true
    languages:
      - en
      - es
  RI:
    redirect_to_online_reg_url: true
    languages:
      - en
      - es
  SC:
    redirect_to_online_reg_url: true
    languages:
      - en
  TN:
    redirect_to_online_reg_url: true
    require_age_confirmation: true
    require_id: false
    languages:
      - en
  UT:
    redirect_to_online_reg_url: true
    languages:
      - en
  VT:
    require_age_confirmation: true
    redirect_to_online_reg_url: true
    require_id: false
    languages:
      - en
  VA:
    redirect_to_online_reg_url: true
    languages:
      - en
    api_settings:
        api_url: "https://externalapi.elections.virginia.gov/v2"
        api_username: "RockTheVote"
        api_key: <%= ENV['VA_API_KEY'] %>
  WA:
    redirect_to_online_reg_url: true
    languages:
      - en
      - es
      - zh
      - vi
      - ko
  WV:
    redirect_to_online_reg_url: true
    languages:
      - en
  WI:
    redirect_to_online_reg_url: true
    languages:
      - en

enabled_locales:
  - en
  - es

pdf:
  nvra:
    page1:
      default_logo: 'pdf/rtvlogo.gif'
      other_block:
        instructions_url: "https://www.rockthevote.org/registration/instructions/<STATE>-<LOCALE>.html"
  
