sponsor:
  barcode_prefix: "RTV"
  name: "Rock the Vote"
  url: "http://www.rockthevote.com"
  facebook_callback_url: <%= CGI.escape("http://www.rockthevote.com/register/fb") %>
  partner_signup_url: "http://www.rockthevote.com/partner"
  footer_link_base_url: "http://www.rockthevote.com/voter-registration/online-application-system"
  footer_copyright: "&copy; Copyright %d, Rock the Vote"
  partner_comarketing_text: |
    Numbers not as high as you'd like?
    <a href="http://www.rockthevote.com/partner/how-to-get-it-out-there.html" target="_blank">Here are some ways to help market your tool.</a>

from_address: "rocky@example.com"
default_url_host: "register.example.com"

admin:
  from_address: "rtv-admins@osuosl.org"
  translation_recipients: "david@rockthevote.com, alex.mekelburg@gmail.com"

admin_username: 'admin'
widget_js_url:  'https://s3.amazonaws.com/ovr/widget_loader.js'

use_https: true
paperclip_options: 
  path: ":rails_root/public/system/:attachment/:id/:style/:filename"
  url: "/system/:attachment/:id/:style/:filename"
delayed_wrap_up: true

mobile_redirect_url: https://register2.rockthevote.com
mobile_browsers:
  - mobile
  - webos
  - blackberry
  - iphone
  
widget_loader_url: https://s3.amazonaws.com/ovr/widget_loader.js
hours_before_first_reminder: 120
hours_between_first_and_second_reminder: 120
pdf_expiration_days: 14
pdf_no_email_expiration_minutes: 10
partner_csv_expiration_minutes: 30

states_with_online_registration:
  - CA
  - NV
  - WA
  
ovr_states:
  CA:
    api_settings:
      api_url: https://covrapitest.sos.ca.gov/PostingEntityInterfaceService.svc
      api_key: d2DE1Nht8I
      web_url_base: http://covrtest.sos.ca.gov
    languages:
      - en
      - es
  NV:
    languages:
      - en
  WA:
    languages:
      - en

  
enabled_locales:
  - en
  - es
  
pdf:
  nvra:
    page1:
      default_logo: 'pdf/rtvlogo.gif'
      other_block:
        instructions_url: "http://www.rockthevote.com/registration/instructions/<STATE>-<LOCALE>.html"
  
